version: '3.8'

services:
  version-compare-api:
    # build: .
    image: version-compare-tool:1.1.0
    ulimits:
      nproc: 8192
      nofile: 65536
    command: >
      uvicorn src.api.main:app
      --host 0.0.0.0
      --port 9112
      --log-level info
    ports:
      - "9112:9112"
    privileged: true
    environment:
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_TOKEN_BI_SERVER=${GITLAB_TOKEN_BI_SERVER}
      - GITLAB_PROJECT_ID_BI_SERVER=${GITLAB_PROJECT_ID_BI_SERVER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=9112
      - DEBUG=false
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9112/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      #- ./main_fixed.py:/app/src/api/main.py
      #- ./index.html:/app/index.html
    networks:
      - version-compare-network

networks:
  version-compare-network:
    driver: bridge

volumes:
  logs: