version: '3.8'

services:
  version-compare-api:
    build: .
    ports:
      - "9112:9112"
    environment:
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_TOKEN_BI_SERVER=${GITLAB_TOKEN_BI_SERVER}
      - GITLAB_PROJECT_ID_BI_SERVER=${GITLAB_PROJECT_ID_BI_SERVER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=9112
      - DEBUG=false
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9112/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - version-compare-network

networks:
  version-compare-network:
    driver: bridge

volumes:
  logs: 